### ISSUE TITLE
UI Element Sizing and Shifting

### ISSUE THREAD

**Issue by aaronlutz** [Surf-Seattle/trim-tabs#8]

**Comment by udomugo** [comment]
I have resolved the size/shifting issue of the tab control panel when a profile goes into active state. The size is not exactly the same when viewed in the non-active profile state, but the difference is not noticeable. The issues was resolved in the utilities.py file, the way the ActiveBar widget was being hidden in the non-active state stored size parameters that would be overridden once the ActiveBar was unhidden, therefore resulting in any kv file adjustments to have no effect during the active state. I am looking at making a better solution as this will only work in the case that we add no other widgets that use the utilities.py hide_widget method. However this has resolved the direct issue with the current features implemented.
